services:
  web:
    build: .
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: .
          target: /code
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - EC2_INSTANCE_UP=${AWS_ACCESS_KEY_ID}
      - EC2_INSTANCE_IP=${AWS_ACCESS_KEY_ID}
      - EC2_USER=${AWS_ACCESS_KEY_ID}