# Black Configuration
[tool.black]
line-length = 100
include = '\.pyi?$'
skip-magic-trailing-comma = true
target-version = ['py310']

# isort Configuration
[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["app"]
multi_line_output = 3
force_grid_wrap = 0
combine_as_imports = true
include_trailing_comma = true
force_single_line = false
skip = ["venv", ".venv", "migrations"]