name: CD Pipeline

on:
  push:
    branches: [master, main, dev]
  pull_request:
    branches: [master, main]

# Source for how this was set up test
# https://dev.to/s3cloudhub/automate-docker-deployments-push-your-images-to-ec2-with-github-actions-3a3j
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug PEM Key Line Count
      run: |
        printf "%s" "${{ secrets.EC2_KEY }}" | grep -c '^'

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t common_assessment_tool .
        docker tag common_assessment_tool ${{ secrets.DOCKERHUB_USERNAME }}/common_assessment_tool:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/common_assessment_tool:latest

    - name: SSH and update EC2 container
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/common_assessment_tool:latest
          docker stop my_app_container || true
          docker rm my_app_container || true
          docker run -d --name my_app_container -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/common_assessment_tool:latest