name: CD Pipeline

on:
  push:
    branches: [master, main, dev]
  pull_request:
    branches: [master, main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - id: deploy
        uses: bitovi/github-actions-deploy-docker-to-ec2@v1.0.2  # https://github.com/marketplace/actions/deploy-docker-to-aws-ec2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_default_region: us-west-2
          aws_elb_app_port: 8000